---
version: 0.2
phases:
  install:
    commands:
      - kubectl version --short --client
  pre_build:
      commands:
        - TAG="$CODEBUILD_BUILD_NUMBER.$(date +%Y-%m-%d.%H.%M.%S).$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
        - echo $TAG
        - echo "${CODEBUILD_WEBHOOK_HEAD_REF}"
        - echo "${BRANCH}"
        - $(aws ecr get-login --no-include-email)
        - export KUBECONFIG=$HOME/.kube/config
        - SOLR_REPOSITORY_URI="${REPOSITORY_URI}solr"
        - sed -i.bak -e 's@VIVO_USERNAME@'"${VIVO_USERNAME}"'@' -e 's@VIVO_PASSWORD@'"${VIVO_PASSWORD}"'@' -e 's@VIVO_HOST@'"${VIVO_HOST}"'@' vivo/example.runtime.properties;
  build:
    commands:
      - |
        if expr "${BRANCH}" : ".*master" >/dev/null || expr "${BRANCH}" : ".*dev" >/dev/null; then
          docker build --tag $REPOSITORY_URI:$TAG ./vivo
          docker build --tag $SOLR_REPOSITORY_URI:$TAG ./vivosolr

        fi
  post_build:
    commands:
      - |
        if expr "${BRANCH}" : ".*master" >/dev/null || expr "${BRANCH}" : ".*dev" >/dev/null; then
          docker push $REPOSITORY_URI:$TAG
          docker push $SOLR_REPOSITORY_URI:$TAG
        fi