kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc
  namespace: vivo
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
#volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
  #iops is multipled by 100 by the number specified
  iopsPerGB: "3"
  fsType: ext4
