apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vivo-tdb-pvc
  namespace: vivo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 100Gi